config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'index', to: 'tasks#index'
  get 'tasks/:id', to: 'tasks#show', as: :show
  get 'new', to: 'tasks#new', as: :new
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update',  as: :update
  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # CRUD
  # Create

  def new
    @task = Task.new
  end
  # create a new task

  def create
    @task = Task.new(parameters)
    @task.save
    redirect_to index_path
  end

  # Read
  # get all tasks
  def index
    @tasks = Task.all
  end

  # get one task

  def show
    @task = Task.find(params[:id])
  end

  # Update
  # update a task

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(parameters)
    redirect_to index_path
  end
  # Destroy
  # destroy a particular task

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to index_path
  end

  def completed?
    @task = Task.find(params[:id])
    if @task.completed
      return @completion = 'This task is completed'
    else
      return @completion = 'This task is not completed yet'
    end
  end

  private

  def parameters
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task, url: update_path do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <% if task.completed %>
        <input type="checkbox" checked disabled>
      <% else %>
        <input type="checkbox" disabled>
      <% end %>
      <%= link_to task.title, show_path(task) %> <%= link_to 'Delete', show_path(task), method: :delete,  data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

<h3><%= link_to '+ Add a new task', new_path %></h3>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<div class="details">
  <p><%= @task.details %></p>
</div>

<% if @task.completed %>
 <input type="checkbox" checked disabled>
<p>This task is completed</p>
<% else %>
 <input type="checkbox" disabled>
<p>This task is not completed yet</p>
<% end %>

<%= link_to 'Edit task', edit_path %>

<%= link_to 'View list of tasks', index_path %>